Sys.unsetenv("http_proxy")
Sys.unsetenv("https_proxy")

install.packages("RWeka")
install.packages("Wordcloud")
install.packages("RColorBrewer")
install.packages("Topicmodels")
install.packages("igraph")
install.packages("syuzhet")
install.packages("tibble")
install.packages("Fragman")


library("RWeka")
library("Wordcloud")
library("RColorBrewer")
library("Topicmodels")
library("igraph")
library("syuzhet")
library("tibble")
library("Fragman")

library("rtweet")
library("httpuv")
library("qdap")
library("qdapRegex")